### ISSUE TITLE
Impossible to open the panel after editing "SuperModerator" "command.refresh" right

### ISSUE THREAD

**Issue by Mkl21** [rifleh700/gradmin#2]
Hello, the admin panel started to do not want to be displayed and I had this error :

`gradmin\core\coroutines.lua:6: gradmin\core\client\guiguard.lua:18: attempt to call global '_guiSetEnabled' (a nil value) [string "?"]`

I had to move the variable `local _guiSetEnabled = guiSetEnabled` in guigard.lua above `cGuiGuard.setPermission()` function to be able to display the admin panel.

**Comment by rifleh700** [comment]
I cant reproduce it. Can u pls download clear gradmin resource and say about what u do for trigger dat error?

**Comment by rifleh700** [comment]
fixed
